[package]
name = "huffnpuff"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3.3"
bitvec = "1.0.1"
serde = "1.0.218"

[dev-dependencies]
serde = { version = "1.0.218", features = ["derive"] }
